### ISSUE TITLE
Solve 1154B - Make Them Equal (1200)

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Competitive-Programming#4]
Problem Link - https://codeforces.com/contest/1154/problem/B
Problem rating: 1200
Tag - math
Platform - Codeforces
Difficulty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation. CPP or just like that with the correct extension.

Make sure this before making PR regarding it :

-> An appropriate title for PR
-> Making another file with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding

**Comment by Vivek2213** [comment]
Hey @Arpitgupta1014 Can I work on this issue.

**Comment by Arpitgupta1014** [comment]
Good work @Vivek2213
