### ISSUE TITLE
Solve 1559C - Mocha and Hiking (1200)

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Competitive-Programming#5]
Problem Link - https://codeforces.com/problemset/problem/1559/C
Problem rating: 1200
Tag - combinatorics, greedy, math
Platform - Codeforces
Difficulty - Intermediate

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension. And in the same folder

Make sure this before making PR regarding it :

-> An appropriate title for PR
-> Making another file with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding

**Comment by amansingh854** [comment]
Hey Arpit Gupta, can I work on this issue?
@Arpitgupta1014

**Comment by Arpitgupta1014** [comment]
Good job @amansingh854
