### ISSUE TITLE
Solution for COINS - Bytelandian gold coins (CodeChef)

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Competitive-Programming#8]
Problem Link - https://www.codechef.com/problems/COINS
Tag - greedy, data structure
Platform - CodeChef
Difficulty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.CPP or just like that with the correct extension. And in the same folder

Make sure this before making PR regarding it :

-> An appropriate title for PR
-> Making another branch with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding 👍

**Comment by suju1811** [comment]
Heyy Arpit !! I want to work on this issue . So could you assign it to me.

**Comment by ashishpetwal** [comment]
Hey @Arpitgupta1014 I would like to work on this issue! Kindly assign to me

**Comment by Arpitgupta1014** [comment]
Sorry @ashishpetwal , As @Siddharth7899 commented first so I assigned this task to him.

**Comment by singhAman05** [comment]
hi @Arpitgupta1014 can i work on this problem

**Comment by Arpitgupta1014** [comment]
Nice job @Siddharth7899
