### ISSUE TITLE
Solve Mancunian And Colored Tree (HackerEarth)

### ISSUE THREAD

**Issue by Arpitgupta1014** [Arpitgupta1014/Competitive-Programming#9]
Problem Link - https://www.hackerearth.com/practice/data-structures/trees/binary-and-nary-trees/practice-problems/algorithm/mancunian-and-colored-tree/
Tag - tree, data structure
Platform - HackerEarth
Difficulty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

-> An appropriate title for PR
-> Making another branch with an appropriate name.
-> Comment on the file at the top with the link to the question
Happy Coding

**Comment by singhAman05** [comment]
sir can i work on this..??

**Comment by Arpitgupta1014** [comment]
Good work @singhAman05
